import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Container from "../components/Container";
import ArticleLink from "../components/Home/ArticleLink";
import { getAllPosts } from "../services/fetchData";
import { GetStaticProps } from "next";
export default function Home({ allPosts }: any) {
  return (
    <>
      <Head>
        <title>Carlo's NextJS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Featured post={allPosts[0]} />
        <div className="grid grid-cols-3 gap-3">
          <LatestPosts allPosts={allPosts} />
          <TopPosts />
        </div>
      </Container>
    </>
  );
}

function Featured({ post }: any) {
  return (
    <Link href={post && post.slug ? `/post/${post.slug}` : "/"}>
      <a>
        <div className="bg-white rounded-md shadow-md mb-5 overflow-hidden">
          <h2 className="font-semibold text-xl p-5">✨ Featured</h2>
          <div className="relative bg-black w-full h-52 overflow-hidden">
            <img
              src={post && post.data.featureImage && post.data.featureImage}
              className="absolute object-cover object-center w-full h-full"
            />
            <div className="absolute w-full h-full bg-black opacity-40"></div>
            <div className="relative flex flex-col space-y-3 px-5 pt-10 text-white">
              <h3 className="text-2xl font-medium">
                {post && post.data.title}
              </h3>
              <p>{post && post.data.shortDesc}</p>
            </div>
          </div>
        </div>
      </a>
    </Link>
  );
}

function LatestPosts({ allPosts }: any) {
  return (
    <div className="bg-white rounded-md p-5 md:col-span-2 col-span-3 shadow-md">
      <h2 className="font-semibold text-xl mb-4">⌛ Latest Posts</h2>
      <div className="flex flex-col space-y-2">
        {allPosts &&
          allPosts.map((post: any) => {
            return (
              <ArticleLink
                key={post.slug}
                title={post.data.title}
                shortDesc={post.data.shortDesc}
                link={`/post/${post.slug}`}
                dateString={post.data.date}
              />
            );
          })}
      </div>
    </div>
  );
}

function TopPosts() {
  return (
    <div className="md:col-span-1 col-span-3 order-first md:order-last">
      <div className="bg-white rounded-md p-5 shadow-md">
        <h2 className="font-semibold text-xl mb-4">🥇 Top Posts</h2>
        <div className="flex flex-col space-y-2">
          <ArticleLink
            title={"Pokemon Is Cool!"}
            shortDesc={"Yeser I love pokemon"}
            link="post/pokemon-is-cool"
          />
        </div>
      </div>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const allPosts = getAllPosts();
  return {
    props: {
      allPosts: allPosts,
    },
  };
};
