import Head from "next/head";
import Image from "next/image";
import Container from "../components/Container";
import ArticleLink from "../components/Home/ArticleLink";

export default function Home() {
  return (
    <>
      <Head>
        <title>Carlo's NextJS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Featured />
        <div className="grid grid-cols-3 gap-3">
          <LatestPosts />
          <TopPosts />
        </div>
      </Container>
    </>
  );
}

function Featured() {
  return (
    <div className="bg-white rounded-md shadow-md mb-5 overflow-hidden">
      <h2 className="font-semibold text-xl p-5">✨ Featured</h2>
      <div className="bg-black w-full h-52"></div>
    </div>
  );
}

function LatestPosts() {
  return (
    <div className="bg-white rounded-md p-5 md:col-span-2 col-span-3 shadow-md">
      <h2 className="font-semibold text-xl mb-2">⌛ Latest Posts</h2>
      <div className="flex flex-col space-y-2">
        <ArticleLink
          title={"Pokemon Is Cool!"}
          shortDesc={"Yeser I love pokemon"}
        />
        <ArticleLink
          title={"I like turtles!"}
          shortDesc={"They're so majestic man. Here are 3 reasons why..."}
        />
        <ArticleLink
          title={"WTF is Boku no Pico?!?"}
          shortDesc={"How can I unwatch this crap bro!"}
        />
      </div>
    </div>
  );
}

function TopPosts() {
  return (
    <div className="md:col-span-1 col-span-3 order-first md:order-last">
      <div className="bg-white rounded-md p-5 shadow-md">
        <h2 className="font-semibold text-xl mb-2">🥇 Top Posts</h2>
        <div className="flex flex-col space-y-2">
          <ArticleLink
            title={"Pokemon Is Cool!"}
            shortDesc={"Yeser I love pokemon"}
          />
          <ArticleLink
            title={"WTF is Boku no Pico?!?"}
            shortDesc={"How can I unwatch this..."}
          />
        </div>
      </div>
    </div>
  );
}
